### ISSUE TITLE
Template blocks lose their properties

### ISSUE THREAD

**Issue by IvorAmlug** [desht/ModularRouters#163]
### Describe the bug

Well it seems like all my template blocks lose their properties after relogin into the world
![2022-04-09_17 41 03](https://user-images.githubusercontent.com/38656481/162581118-3b923500-4d8c-4f92-981e-e6348a411568.png)
d
This is how they look after rejoin or sometimes after reloading the chunk.
![2022-04-09_17 42 35](https://user-images.githubusercontent.com/38656481/162581161-c78d905e-9725-4e6c-a7de-d9e1b3652db1.png)
This is how they should look like.
But not only do they lose their textures they also lose all the properties of the Mimic Agument (how hard they are to break etc)

### How to reproduce the bug

Use an Extruder Mk2 Module extend any type of block except of Iron bars or fences they dont seem to Properly work whit the Template blocks in General.
Relog into the world and there u go

### Expected behavior

Well the Template blocks should keep their properties. After Relogin or Reloadin the chunk.

### Additional details

Even tho the screenshots show shaders those are not required to reproduce
I removed Optifine Completly to check.
Forge version: 39.1.2
Modular Routers version: 1.18.1-9.0.2-85

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Oops, yeah.  Somehow the NBT saving code for the block entity wasn't saving the camouflage.  Will be fixed in next release.

**Comment by IvorAmlug** [comment]
Perfect

**Comment by MCSuchter** [comment]
This seems to happen again with Modular Routers 12.0.2 for 1.20.1 (Tested in Modpack ATM9 0.2.32) additionally it also spams the console with

```
[17:19:12] [Server thread/ERROR] [minecraft/LevelChunk]: A BlockEntity type me.desht.modularrouters.block.tile.TemplateFrameBlockEntity has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because "p_129203_" is null
	at net.minecraft.nbt.NbtUtils.m_129202_(NbtUtils.java:254) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at me.desht.modularrouters.block.tile.TemplateFrameBlockEntity.m_183515_(TemplateFrameBlockEntity.java:75) ~[modular-routers-12.0.2+mc1.20.1.jar%23734!/:12.0.2+mc1.20.1]
	at net.minecraft.world.level.block.entity.BlockEntity.m_187482_(BlockEntity.java:77) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.world.level.block.entity.BlockEntity.m_187480_(BlockEntity.java:64) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_8051_(LevelChunk.java:376) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_63454_(ChunkSerializer.java:324) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.level.ChunkMap.m_140258_(ChunkMap.java:829) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.level.ChunkMap.m_198874_(ChunkMap.java:796) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:490) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:454) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:316) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23885!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
Was using a extruder mk2 with a mimic augment and grass blocks, the modular router also had a camouflage upgrade as a grass block

**Comment by JeNoVaViRuS** [comment]
I have this issue in version 13.2.3 (1.21.1 in Stoneblock 4) when joining the server or after coming back from another dimension. As soon as they are "removed" and then extruded again they look normal. 

Here is one router in the floor that extrudes 3 blocks upwards:
<img width="450" height="412" alt="Image" src="https://github.com/user-attachments/assets/e8777f83-4b3b-41f2-aae2-2f507ae7a003" />
