### ISSUE TITLE
Server Crash/Corruption issues

### ISSUE THREAD

**Issue by unit285** [desht/ModularRouters#80]
### Describe your problem, including steps to reproduce it
Modular Router with 9 speed upgrades and a camo upgrade. 

Slot 1 had a Puller Module Mk2 pulling charcoal from a storage drawer.
The rest of the 8 router slots were all identical with Sender Module Mk2 With Regulator Augment sending Charcoal to 8 different Powah Furnators whenever the targeted Furnator had less than 64 Charcoal.

Issues started when I broke the storage drawer and left the router untouched. Issues included server crashes and timeouts. Eventually entire chunks around the area stopped loading.

**Comment by Ki-Tan2934** [comment]
Can confirm

Gives the client crashes with this error

java.lang.ExceptionInInitializerError: null
	at net.minecraft.client.gui.fonts.FontResourceManager.func_212318_b(SourceFile:152) ~[?:?] {re:classloading}
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_231] {}
	at net.minecraft.client.gui.fonts.FontResourceManager.func_211504_a(SourceFile:151) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:408) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[1.15.2.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.20.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.rehash(ObjectOpenCustomHashSet.java:683) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.addOrGet(ObjectOpenCustomHashSet.java:360) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at net.minecraft.client.renderer.RenderType$Type.func_228676_c_(SourceFile:655) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.RenderType$Type.func_228675_b_(SourceFile:638) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.RenderType.func_228633_a_(SourceFile:402) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.RenderType.func_228658_l_(SourceFile:320) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.fonts.EmptyGlyph.<init>(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.Font.<clinit>(SourceFile:30) ~[?:?] {re:classloading}
	... 15 more

Can Timeout / Crash a server upon connecting next to effected blocks

**Comment by desht** [comment]
@Ki-Tan2934 please use pastebin or similar for stacktraces, don't post directly in issues.  Also, please post a full log because there's nothing in there that indicates anything to do with Modular Routers.

@unit285 I need to see some actual crash logs / stacktraces.  I can't reproduce your problem - when I break any inventory that a puller is pulling from, the router just stops, as expected.

**Comment by Ki-Tan2934** [comment]
You have to wait around after doings so. That is client crash log there no
server crash log, as the server stalls till watchdog kicks in and restarts.

Its 're produceable on the atm5 mod pack and the problem stops after the
lock is removed.

**Comment by desht** [comment]
Nope, sorry, can't reproduce this at all.  Spent about an hour messing around (on dedicated server, not just my dev world) with various inventories including storage drawers.  Pulling from the drawer with 9 upgrades, sending items out to other inventories with Sender Mk2 & regulators.... break the drawer, move it (with a Mek cardboard box)... doesn't matter, the router is behaving absolutely fine.

What leads you to believe that it's even the router causing these lockups?  Because it's sounding like coincidence to me at this point.

**Comment by Ki-Tan2934** [comment]
Client crash as soon as joining when block was removed was able to join.

Second when server was reset when ever a player joined the server in that
area world was black and would not load server stalled. I can provide a
region file that was affecting the area

**Comment by Ki-Tan2934** [comment]
Here a region file that was affected
https://drive.google.com/file/d/1fyCwjh9hEbDzIQwb5IKjYdG0z5FU6Uhu/view?usp=sharing

Mod pack atm5

**Comment by desht** [comment]
I need to see your *complete client log*.  Region files don't help.  Client log please.

When you say "block was removed", you mean the Item Router?  And if the world was "corrupted", how did you remove the block?

**Comment by Ki-Tan2934** [comment]
ok hang on

**Comment by Ki-Tan2934** [comment]
https://pastebin.com/bx5DnnY1  I have 9 crash logs of sure
https://pastebin.com/94DA0pyt  Last crash log

**Comment by desht** [comment]
None of that appears to be related to Modular Routers in any way.

Sorry, but I simply don't have enough information to debug this.  Maybe it's happening, but I can't reproduce it, and nothing you've told me so far gives me any more clues to start looking.
